[package]
name = "message-io"
version = "0.7.0"
authors = ["lemunozm <lemunozm@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
description = "Easy asynchronous network message library"
homepage = "https://github.com/lemunozm/message-io/"
repository = "https://github.com/lemunozm/message-io/"
keywords = ["network", "message", "asynchronous", "events"]
categories = ["asynchronous", "game-development", "network-programming", "rust-patterns", "encoding"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
mio = { version = "0.7", features = ["os-poll", "tcp", "udp"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"
crossbeam = "0.8"
log = "0.4"
net2 = "0.2.34"
num_enum = "0.5.1"
strum = { version = "0.20", features = ["derive"] }
url = "2.2.0"

#![cfg_attr(test, feature(proc_macro))]
#[cfg(test)]
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.3"
serde-big-array = "0.3"
fern = "0.6.0"
chrono = "0.4.19"
test-case = "1.1.0"
rand = "0.8.3"

[[bench]]
name = "performance"
harness = false

[[example]]
name = "adapter_template"
crate-type = ["staticlib"]
