[package]
name = "message-io"
version = "0.1.0"
authors = ["lemunozm <lemunozm@gmail.com>"]
edition = "2018"

[dependencies]
mio = { version = "0.7", features = ["os-poll", "tcp", "udp"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"
crossbeam-channel = "0.4.2"

